PIP-545 add flag to skip loop calling
ENCODE-DCC/hic-pipeline pull request #35
Opened 2019-03-14 17:11 UTC by p-sud

2019-03-15 17:11 UTC, gabdank requested changes
can we add a test that shows no loops production?

2019-03-15 17:21 UTC, p-sud commented
The entrypoint into hic.wdl from hic files works, then yes, it should be doable. We can add a workflow test using the inter_30 in the test_data. There isn't a good way to check for the lack of existence of an output, though, so we'd probably need to add a python script to check the outputs in the metadata.json

2019-03-18 15:52 UTC, p-sud commented
Added test for skipping loop calling, with entrypoint from a hic file

2019-03-18 16:09 UTC, gabdank approved these changes

2019-03-18 16:09 UTC, merged